# Generated by Django 4.0.4 on 2022-06-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_customuser_last_name_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='use_profile/download.jfif', upload_to='user_profile'),
        ),
    ]
