# Generated by Django 4.0.4 on 2022-06-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_customuser_addres_alter_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user_profile/download.jfif', upload_to='user_profile'),
        ),
    ]
